# action.yml
name: 'Hello World'
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start action
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: docker build
        run: make docker
      - name: docker run
        run: make start
      - uses: actions/checkout@v3
